# Generated by Django 5.2.1 on 2025-05-19 15:19

import users.user_manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.user_manager.CustomUserManager()),
            ],
        ),
    ]
