# Generated by Django 4.2 on 2025-05-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('experiments', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_summary', models.TextField()),
                ('conclusion', models.TextField()),
                ('significance', models.CharField(choices=[('breakthrough', 'Breakthrough'), ('important', 'Important'), ('moderate', 'Moderate'), ('minor', 'Minor')], max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='experiments.experiment')),
                ('tags', models.ManyToManyField(blank=True, related_name='findings', to='projects.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
